services:
  - type: web
    name: navidrome
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: ND_MUSICFOLDER
        value: /music
      - key: ND_DATAFOLDER
        value: /data
